# Generated by Django 4.1.7 on 2023-04-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50, null=True)),
                ("aadhar_num", models.IntegerField(null=True)),
                ("From", models.CharField(max_length=50, null=True)),
                ("To", models.CharField(max_length=50, null=True)),
                ("date", models.DateField(max_length=50, null=True)),
                ("no_of_seats", models.IntegerField(null=True)),
                ("Class", models.CharField(max_length=50, null=True)),
                ("username", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
