# Generated by Django 4.1.7 on 2023-04-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bticket", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="ticket", name="Class",),
        migrations.AddField(
            model_name="ticket", name="price", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="aadhar_num",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
