# Generated by Django 4.1.7 on 2023-04-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bticket", "0002_remove_ticket_class_ticket_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
