# Generated by Django 4.1.7 on 2023-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bticket", "0003_alter_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
